#!/bin/bash
# File name: tomo_run.pbs
#PBS -A mat134
#PBS -l walltime=2:00:00
#PBS -l nodes=32
#PBS -l gres=atlas1%atlas2

cd /lustre/atlas1/cli106/scratch/2ya/tomo/tomo_real

export ROOT_CT_DIR="/lustre/atlas1/cli106/scratch/2ya/tomo/tomo_real/data"

module load PrgEnv-pgi
module load cudatoolkit
export CRAY_CUDA_PROXY=1


export EXP_CT_NAME="CT_Aluminum_ironcenter_0090"
aprun -n 32 -N 1 ./projections_to_sinogram_hpc

export EXP_CT_NAME="Derek_injec_0040"

aprun -n 32 -N 1 ./projections_to_sinogram_hpc

export  EXP_CT_NAME="TURBINECT_0010"

aprun -n 32 -N 1 ./projections_to_sinogram_hpc

export EXP_CT_NAME="TURBINECT_0180"

aprun -n 32 -N 1 ./projections_to_sinogram_hpc